# Generated by Django 4.2 on 2023-04-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monica', '0002_post_delete_birthdaymessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
